services:
  ubuntu:    
    build: mine
    image: mine:latest
    
    # Make some storage from outside of the container available within the container.
    # Changes made here from inside the container will persist beyond the container lifetime.
    volumes:
      - type: bind
        source: H:\
        target: /mnt/persist

    # Connect using Remote Desktop to localhost:3390.
    ports:
      - "3390:3389"
